swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /bancos/:
    get:
      tags:
      - bancos
      description: get Banco si tiene codigos registrados
      operationId: BancoController.GetAll
      responses:
        "200":
          description: ""
          schema:
            type: array
            items:
              $ref: '#/definitions/models.BancosPorCodigo'
        "400":
          description: ""
  /cuenta_bancaria_banco/:
    get:
      tags:
      - cuenta_bancaria_banco
      description: get Cuenta_bancaria_banco
      operationId: CuentaBancariaBancoController.GetAll
      parameters:
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            type: array
            items:
              $ref: '#/definitions/models.CuentaBancariaBanco'
        "400":
          description: ""
  /cuenta_bancaria_banco/{id}:
    get:
      tags:
      - cuenta_bancaria_banco
      description: get Cuenta_bancaria_banco by id
      operationId: CuentaBancariaBancoController.GetOne
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.CuentaBancariaBanco'
        "400":
          description: :id is empty
  /solicitud_avance/:
    get:
      tags:
      - solicitud_avance
      description: get Solicitud_avance
      operationId: SolicitudAvanceController.GetAll
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Solicitud_avance'
        "403":
          description: ""
    post:
      tags:
      - solicitud_avance
      description: create Solicitud_avance
      operationId: SolicitudAvanceController.Create
      parameters:
      - in: body
        name: body
        description: body for Solicitud_avance content
        required: true
        schema:
          $ref: '#/definitions/models.Solicitud_avance'
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/models.Solicitud_avance'
        "403":
          description: body is empty
  /solicitud_avance/{id}:
    get:
      tags:
      - solicitud_avance
      description: get Solicitud_avance by id
      operationId: SolicitudAvanceController.GetOne
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Solicitud_avance'
        "403":
          description: :id is empty
    put:
      tags:
      - solicitud_avance
      description: update the Solicitud_avance
      operationId: SolicitudAvanceController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Solicitud_avance content
        required: true
        schema:
          $ref: '#/definitions/models.Solicitud_avance'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Solicitud_avance'
        "403":
          description: :id is not int
    delete:
      tags:
      - solicitud_avance
      description: delete the Solicitud_avance
      operationId: SolicitudAvanceController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
definitions:
  models.BancosPorCodigo:
    title: BancosPorCodigo
    type: object
    properties:
      Activo:
        type: boolean
      CodigoAch:
        type: integer
        format: int64
      CodigoSuper:
        type: integer
        format: int64
      IdTercero:
        type: integer
        format: int64
      NIT:
        type: string
      NombreBanco:
        type: string
  models.CuentaBancariaBanco:
    title: CuentaBancariaBanco
    type: object
    properties:
      Id:
        type: integer
        format: int64
      NombreBanco:
        type: string
      NombreSucursal:
        type: string
      NumeroCuenta:
        type: integer
        format: int64
  models.Solicitud_avance:
    title: Solicitud_avance
    type: object
tags:
- name: cuenta_bancaria_banco
  description: |
    CuentaBancariaBancoController operations for cuenta_bancaria_banco
- name: solicitud_avance
  description: |
    SolicitudAvanceController operations for Solicitud_avance
- name: bancos
  description: |
    BancoController operations for cuenta_bancaria_banco
